####################################################################
# Authors: Ahmad Aji Santoso
# Email: ahmad21@student.ub.ac.id
####################################################################

---
- name: Init Swarm Manager
  hosts: managers
  become: true
  gather_facts: False
  remote_user: ubuntu
  vars:
    manager: "{{ hostvars[groups['managerprivateip'][0]]['inventory_hostname'] }}"
    stackfile_src: "/vagrant/aws-terraform-swarm/swarm-cluster-6node/stackfile/"
    stackfile_dest: "/home/ubuntu/"
  tasks:
  
    - name: Install Plugin vieux/sshfs
      command: docker plugin install --grant-all-permissions vieux/sshfs

    - name: Create a directory mdl-stackfile
      file:
        path: "{{ stackfile_dest }}mdl-stackfile"
        state: directory
        mode: "0755"
      register: stackfile_folder

    - name: Copy Makefile To Manager
      copy:
        src: "{{ stackfile_src }}Makefile"
        dest: "{{ stackfile_folder.path }}"

    - name: Copy Stackfile To Manager
      copy:
        src: "{{ stackfile_src }}mdl-stackfile.yml"
        dest: "{{ stackfile_folder.path }}"

    - name: Swarm Init
      command: docker swarm init  --advertise-addr {{ manager }}

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug:
        var: worker_token.stdout

- name: Join Swarm Cluster
  hosts: workers
  become: true
  remote_user: ubuntu
  gather_facts: False
  vars:
    token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
    manager: "{{ hostvars[groups['managerprivateip'][0]]['inventory_hostname'] }}"
  tasks:

    - name: Install Plugin vieux/sshfs
      command: docker plugin install --grant-all-permissions vieux/sshfs

    - name: Join Swarm Cluster as a Worker
      command: docker swarm join --token {{ token }}  {{ manager }}:2377
      register: worker

    - name: Show Results
      debug:
        var: worker.stdout

    - name: Show Errors
      debug:
        var: worker.stderr

- name: Adding Label For Worker
  hosts: managers
  become: true
  gather_facts: False
  remote_user: ubuntu
  tasks:
    - name: Set Label For Worker 2 moodleworker
      command: docker node update --label-add moodleworker=true worker-2
      register: labelsmdlworker2

    - name: Show Results
      debug:
        var: labelsmdlworker2.stdout

    - name: Show Errors
      debug:
        var: labelsmdlworker2.stderr

    - name: Set Label For Worker 3 moodleworker
      command: docker node update --label-add moodleworker=true worker-3
      register: labelsmdlworker3

    - name: Show Results
      debug:
        var: labelsmdlworker3.stdout

    - name: Show Errors
      debug:
        var: labelsmdlworker3.stderr

    - name: Set Label For Worker 4 moodleworker
      command: docker node update --label-add moodleworker=true worker-4
      register: labelsmdlworker4

    - name: Show Results
      debug:
        var: labelsmdlworker4.stdout

    - name: Show Errors
      debug:
        var: labelsmdlworker4.stderr
